# Generated by Django 4.2.13 on 2024-07-29 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('steam_title', models.CharField(max_length=200)),
                ('steam_price', models.CharField(max_length=20)),
                ('aband_title', models.CharField(max_length=200)),
                ('aband_price', models.CharField(max_length=20)),
                ('gog_title', models.CharField(max_length=200)),
                ('gog_price', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
